config/routes.rb
Spider::Application.routes.draw do

  authenticated :user do
    get '/' => "alerts#index"
  end
  get '/' => "home#index"

  resources :alerts

  post 'feedback', to: 'feedback#create'

  devise_for :users, :path => '', :path_names => { :sign_in => 'login', :sign_up => 'new', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification' }
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root 'alerts#index'

  

end

app/models/alert.rb
class Alert < ActiveRecord::Base

  belongs_to :user

  validates_numericality_of :run_every, :greater_than => 3599

  validates_numericality_of :price_min, :greater_than => 0, :allow_blank => true

  validates_numericality_of :price_max, :greater_than => 0, :allow_blank => true

def self.mailer

	require 'Tap'

	now = DateTime.now

	alerts = Alert.where('scheduled_time < ?', now)

	alerts.each do |a|

		last_run = a.scheduled_time - a.run_every.seconds

		tap = Tap.new

		tap.build_query(a, last_run.to_i)

	    results = tap.make_request

	    # puts 'hello'

		if (results['num_matches'] > 0)

			user = User.find(a.user_id)
			message = Array.new

			# puts a.inspect
			
			title = 'Spiderlist results '
			if (!a.terms.blank?)
				title << 'for '+a.terms
			end

			if (!a.zipcode.blank?)
				title << ' near '+a.zipcode
			end

			results['postings'].each do |r|

		    	row = {'source' => r['source'], 
		    		'url' => r['external_url'], 
		    		'price' => r['price'],
		    		'timestamp' => Time.at(r['timestamp']).in_time_zone(user.time_zone).strftime('%m/%d/%Y at %I:%M%p'),
		    		'title' => r['heading'],
		    		'address' => r['location']['formatted_address']}
		    	message << row
		    end

		    if (results['num_matches'] > 10)
		    	additional = results['num_matches'].to_i - 10
		    	footer = "... and " + additional.to_s + " more results "
		    end

			a.scheduled_time = now + a.run_every.seconds
			a.save

			email = AlertMailer.send_alert_email(user, message, title, footer, a)

			email.deliver

			puts email.to_s

		end

	end

  end
  
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]

  # Devise Auth
  before_filter :authenticate_user!, :load_tap
  
  # 
  # cancan auth
  load_and_authorize_resource

  # GET /alerts
  # GET /alerts.json
  def index

    user = current_user

    @alerts = Alert.where(["user_id = ?", user.id])
    
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show

    self.display_results(params['page'])

    @title = 'Latest results '
    if (!@alert.terms.blank?)
      @title << 'for '+@alert.terms
    end

    if (!@alert.zipcode.blank?)
      @title << ' near '+@alert.zipcode
    end

    @page = @next_page - 1
    @prev_page = @page - 1
    
    # 
    # The best way to not write it twice
    @pager = Array.new

    if ((@next_page >= 0) && (@prev_page < 0))
      # page = @page.to_i
      # if page >= 1
        @pager << ActionController::Base.helpers.link_to("Previous Page", '', :class => 'button disabled small')
      # end

      # @pager << @prev_page.to_s + '|' + @page.to_s + '|' + @next_page.to_s
      # if (@next_page != 0)
        @pager << ActionController::Base.helpers.link_to('Next Page', url_for(:page => @next_page.to_s), :class => 'button small')
      # end
    elsif ((@next_page >= 1) && @page > 0)
      @pager << ActionController::Base.helpers.link_to("Previous Page", url_for(:page => @prev_page.to_s), :class => 'button small')
      # end
      # @pager << @page
      # if (@next_page != 0)
      @pager << ActionController::Base.helpers.link_to('Next Page', url_for(:page => @next_page.to_s), :class => 'button small')
    end
    # @pager << @page
    # @pager << @next_page
    #######################################################

    # self.send_results

  end

  # GET /alerts/new
  def new
    # @alert = Alert.new(alert_params)

  end

  # GET /alerts/1/edit
  def edit
    
    # @tap_categories = @tap.categories
    # @tap_radii = @tap.radii
    
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = Alert.new(alert_params)

    @alert.user_id = current_user.id
    @alert.scheduled_time = Time.new + 2.minutes

    current_user.time_zone = cookies['browser.timezone']
    current_user.save

    respond_to do |format|
      if @alert.save
        format.html { redirect_to alert_path(@alert), notice: 'Alert was successfully created.' }
        format.json { render action: 'show', status: :created, location: @alert }
        # 
        # 
        @alert.extend AlertsHelper
        @alert.geocode
        # 
        # 
      else
        format.html { render action: 'new' }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update

    @alert.scheduled_time = Time.new + 2.minutes

    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to alert_path(@alert), notice: 'Alert was successfully updated.' }
        format.json { head :no_content }
        # 
        # 
        @alert.extend AlertsHelper
        @alert.geocode
        # 
        # 
      else
        format.html { render action: 'edit' }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url }
      format.json { head :no_content }
    end
  end


  def display_results(page = nil)

    # @debug = page.to_s

    @query = @tap.build_query(@alert, 0, page)

    results = @tap.make_request

    # @debug = cookies['browser.timezone']

    results['postings'].each do |r|
      # Fix $-1.0
      if (r['price'].blank?)
        r['price'] = '$--'
      elsif (r['price'] <= 0)
        r['price'] = '$--'
      elsif
        r['price'] = '$'+r['price'].to_s
      end

      # @debug = current_user.time_zone

      # r['timestamp'] = 

    end

    @results = results['postings']
    # @tap_results = results.inspect
    # @query = @tap.get_query
    @next_page = results['next_page']

    # @debug = results.to_s
    # @debug = page.to_s + '|' + @next_page.to_s

  end


  def load_tap
      require 'Tap'
      @tap = Tap.new
      @tap_categories = @tap.categories 
      @tap_radii = @tap.radii
      @tap_time_options = @tap.time_options
    end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:zipcode, :radius, :price_min, :price_max, :terms, :category, :run_every)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper

	require 'net/http'
	require 'json'
	
	def geocode
	    response = Net::HTTP.get_response("maps.googleapis.com","/maps/api/geocode/json?address="+self.zipcode.to_s+"&sensor=false")
	    json = JSON.parse(response.body) ##this must show the JSON contents
	    if (!json['results'][0].nil?)
	      lat = json['results'][0]['geometry']['location']['lat']
	      long = json['results'][0]['geometry']['location']['lng']
	    end

	    self.lat = lat
	    self.long = long

	    self.save
	end

end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="large-8 columns">
    <div class="field">  
      <%= f.label :terms, 'What are you looking for?' %><br/>
      <%= f.text_field :terms, :placeholder => "Honda Civic, guitar, 1 Bedroom" %>
      <span class="help">Try broad search terms, like stainless pot or road bike to get more results.  You can use quotes to search for the exact term, like "Dumb and Dumber".  If you search for honda civic, toyota prius your search will turned into "Honda Civic" OR "Toyota Prius", returning exact matches for either.</span>
    </div>
  </div>

  <div class="large-4 columns">
    <div class="field">
      <%= f.label :category, 'Category' %><br/>
      <%= f.select(:category, @tap_categories, { include_blank: true }, {:class => 'chosen-select'}) %>
      <span class="help">Search by general category like All Vehicles, or by something more specific like Real Estate - Apartments.</span>
    </div>
  </div>

</div>

<div class="row">
  <div class="large-6 columns">
    <div class="field">  
      <%= f.label :zipcode, 'Where?' %><br/>
      <%= f.text_field :zipcode,  :placeholder => "ZIP code"  %>
    </div>
  </div>
  <div class="large-6 columns">
    <div class="field">  
      <%= f.label :radius, 'Within' %><br/>
      <%= f.select(:radius, @tap_radii, {}, {:class => 'chosen-select'}) %>
    </div>
  </div>
</div>


<div class="row">

  <div class="large-3 columns">
    <div class="field-price">  
      <%= f.label :price_min, "Minimum Price" %><br/>
      <span class="dollar">$</span><%= f.text_field :price_min,  :placeholder => "USD" %>
    </div>
  </div>

  <div class="large-3 columns">
    <div class="field-price">  
      <%= f.label :price_max, "Maximum Price" %><br/>
      <span class="dollar">$</span><%= f.text_field :price_max,  :placeholder => "USD" %>
    </div>
  </div>

  <div class="small-6 columns">
    <div class="field">
      <%= f.label :run_every, 'How often should we email you the results?' %><br>
      <%= f.select(:run_every, @tap_time_options, {}, {:class => 'chosen-select'}) %>
      <span class="help">We'll never email you more often than this, unless you're resetting your password.  And we'll never email unless we find something relevant.</span>
    </div>
  </div>

</div>


<div class="row">
  <div class="small-6 columns">
    <div class="actions">
      <%= f.submit "Submit", :class => 'button' %> <%= link_to "Cancel", root_path, :class => 'button' %>
    </div>
  </div>
</div>

<% end %>

app/views/alerts/_pager.html.erb
<% if (!@pager.blank?) %>
	<ul class="pager inline-list large-centered large-4 columns">
	<% @pager.each do |p| %>
		<li><%= p %> </li>
	<% end %>
	</ul>
<% end %>

app/views/alerts/_results.html.erb
<div class="large-12 columns">

	<% if current_user.admin? %>
		<%= @query %>

		<%= @debug %>
	<% end %>

	<%= render 'pager' %>

	<hr/>

	<ul class="zebra">
		<% if !@results.blank? %>
			<% @results.each do |r| %>
				<li class="row">
					<ul class="result row">
						<li class="large-6 columns"><%= link_to r['heading'], r['external_url'], :target => "_blank" %></li>
						<li class="large-2 columns"><%= Time.at(r['timestamp']).in_time_zone(current_user.time_zone).strftime('%m/%d/%Y at %I:%M%p') %></li>
						<li class="large-2 columns"><%= r['location']['formatted_address'] %></li>
						<li class="large-2 columns"><%= r['price'] %> | <%= r['source'] %></li>
					</ul>
				</li>
			
			<% end %>
		<% else %>
			<li>No results right now... You'll get an email when the bot finds something!  Or, you can <%= link_to('try a broader search', edit_alert_path(@alert)) %>.</li>
		<% end %>
	</ul>

	<hr/>

	<%= render 'pager' %>
	
</div>

app/views/alerts/edit.html.erb
<h1>Edit alert</h1>

<% if notice %>
	<div class="large-12 columns">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>

<%= render 'form' %>

app/views/alerts/index.html.erb
<div class="large-8 columns">
  <h1>Your Alerts</h1>
</div>

<div class="large-4 columns">
  <%= link_to 'Add a new alert »', new_alert_path, :class => "button large expand" %>
</div>

<% if notice %>
  <div class="large-12 columns">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div class="large-8 columns">
  <table>
    <thead>
      <tr>
        <th>What?</th>
        <th>Where?</th>
        <th>View</th>
        <th>Edit</th>
        <th>Stop</th>
      </tr>
    </thead>

    <tbody>
      <% @alerts.each do |alert| %>
        <tr>
          <td><%= alert.terms %></td>
          <td><%= alert.zipcode %></td>
          <td><%= link_to 'View Results', alert_path(alert) %></td>
          <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
          <td><%= link_to 'Stop', alert, method: :delete, data: { confirm: 'Are you sure?  This will immediately remove this alert from your account.' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if @alerts.empty? %>
    <p>No active alerts.  <%= link_to('Add one now', new_alert_path) %>.</p>
  <% end %>
</div>

<div class="large-4 columns">
<h3>Getting started</h3>
<p><strong>Alerts</strong> are just a set of criteria describing what you're looking for.</p>
<p>Click "add alert" above to start our bot searching for what you want.  It will e-mail you when it finds items matching your criteria, with a link to view all the results if there are too many for the email.</p> 
<p>Once you create an alert, you can edit or remove it at any time.</p>
<p>Once you add an alert, you'll be able to find it on this page.  If there are too many results to fit into an email, you can browse them in full here.</p>
<p>That's pretty much it!</p>
</div>

app/views/alerts/new.html.erb
<div class="row">
	<div class="large-8 columns">
		<h1>Start watching!</h1>
		<%= render 'form' %>
	</div>

	<div class="large-4 columns">
		<h2>A few tips...</h2>
		<ul>
			<li>You can always edit this later!</li>
			<li>Fewer options means more alerts.</li>
			<li>More options means more relevant results.</li>
			<li>We only email you 10 results at a time, but you can always view all your results by going to your dash here on the site.</li>
		</ul>
	</div>
</div>

app/views/alerts/show.html.erb
<% if notice %>
	<div class="large-12 columns">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>

<div class="large-12 columns">
<h1><%= @title %></h1>

	<%= link_to 'Back to list', root_path, :class => 'button' %><%= link_to 'Edit This Alert', edit_alert_path(@alert), :class => 'button right' %>

	<%= render 'results' %>

</div>