config/routes.rb
Spider::Application.routes.draw do

  authenticated :user do
    get '/' => "alerts#index"
  end
  get '/' => "home#index"

  resources :alerts

  post 'feedback', to: 'feedback#create'

  devise_for :users, :path => '', :path_names => { :sign_in => 'login', :sign_up => 'new', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification' }
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root 'alerts#index'

  

end

app/models/feedback.rb
class Feedback

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :body, :email

  validates :body, :presence => true
  validates :email, :presence => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController

  def create
    params[:feedback][:email] = current_user.email

    @message = Feedback.new(params[:feedback])

    if @message.valid?
      FeedbackMailer.new_feedback(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash[:notice] = 'Please enter a message.'
      render :new
    end
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedback/_form.html.erb
<% if user_signed_in? %>
	<div id="feedback" class="row">
		<div class="large-12 columns">
			<h3>We want your feedback!</h3>
			<p>Help us make Spiderist more awesome.</p>
			<%= form_for @message, :url => feedback_path, :html => { :honeypot => true } do |form| %>

			    <div class="field">
			      <%= form.text_area :body, :placeholder => 'Tell us what you like about the site, or what could use improvement.' %>
			    </div>

			    <%= form.submit "Send", :class => 'button small' %>

			<% end %>
		</div>
	</div>
<% end %>

app/views/feedback/new.html.erb
<% if notice %>
  <div class="large-12 columns">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<%= render 'form' %>