config/routes.rb
Spider::Application.routes.draw do

  authenticated :user do
    get '/' => "alerts#index"
  end
  get '/' => "home#index"

  resources :alerts

  post 'feedback', to: 'feedback#create'

  devise_for :users, :path => '', :path_names => { :sign_in => 'login', :sign_up => 'new', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification' }
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root 'alerts#index'

  

end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="row">
		<p>Spiderlist is a part-time project of <%= link_to('Aaron Smith', 'http://aaronsmith.co/') %> and is under active development.  Your feedback is appreciated!</p>
	</div>
</div>

app/views/layouts/_menu.html.erb
<div class="sticky">
	<nav class="top-bar">
		<ul class="title-area">
			<li class="name">
				<h1><a href="/">Spiderlist.org (alpha)</a></h1>
			</li>
			<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
			<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		</ul>
		<section class="top-bar-section">

			<ul class="right">
				<% if user_signed_in? %>
					<% if current_user.admin? %>
						<li><%= link_to "Admin Panel", rails_admin.dashboard_path %></li><li class="divider"></li>
					<% end %>

					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li><li class="divider"></li>
					<li><%= link_to "Edit My Account", edit_user_registration_path %></li><li class="divider"></li>
					<li><%= link_to 'My Alerts', alerts_path %></li><li class="divider"></li>
				<% end %>
				<li class='social'><a target="_blank" href="https://twitter.com/spiderlist" class="webicon twitter">@spiderlist</a></li><li class="divider"></li>
				<li class="social"><a target="_blank" href="https://www.facebook.com/spiderlist" class="webicon facebook">Follow us on Facebook</a></li>
			</ul>
		</section>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spiderlist | Searching Classifieds for You</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>

  <%= render 'layouts/menu' %>

  <div class="row">
  	<%= yield %>
  </div>

  <%= render 'feedback/form' %>

  <%= render 'layouts/footer' %>

  <% if Rails.env == 'production' %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-36906991-2', 'spiderlist.org');
      ga('send', 'pageview');
    </script>
  <% end %>

  </body>
</html>

app/views/layouts/application.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }

  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  -# Set the viewport width to device width for mobile
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

  %title= content_for?(:title) ? yield(:title) : "Untitled"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tag

%body

  = yield

  = javascript_include_tag "application"

:plain
  </html>